name: mascotgirl_ver2
channels:
  - pytorch
  - nvidia
  - ilastik-forge
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - blas
  - bleach
  - brotli
  - brotlipy
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - cryptography
  - cudatoolkit
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - executing
  - flit-core
  - fonttools
  - freetype
  - icc_rt
  - icu
  - idna
  - importlib-metadata
  - importlib_resources
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab_pygments
  - jupyterlab_widgets
  - kiwisolver
  - libpng
  - libsodium
  - libtiff
  - libuv
  - libwebp
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - nest-asyncio
  - notebook
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pandoc
  - pandocfilters
  - parso
  - pickleshare
  - pillow
  - pip
  - prometheus_client
  - prompt-toolkit
  - psutil
  - pure_eval
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - python=3.10
  - python-dateutil
  - python-fastjsonschema
  - python_abi
  - pytorch=2.4.1
  - pytorch-mutex
  - pywin32
  - pywinpty
  - pyzmq
  - qt
  - requests
  - scipy
  - send2trash
  - setuptools
  - sip
  - six
  - soupsieve
  - sqlite
  - stack_data
  - terminado
  - tinycss2
  - tk
  - torchaudio=2.4.1
  - torchvision=0.19.1
  - tornado
  - traitlets
  - typing_extensions
  - urllib3
  - vc
  - vs2015_runtime
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - win_inet_pton
  - wincertstore
  - winpty
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - pytorch-cuda=12.1
  - pydantic
  - conda-3rdparty